testing

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -53,8 +53,8 @@ jobs:
         run: |
           set -e
           if ! cd cmd/windsor; then
-          echo "Failed to navigate to the Windsor CLI directory."
-          exit 1
+            echo "Failed to navigate to the Windsor CLI directory."
+            exit 1
           fi
         
           if ! go build -o "${{ github.workspace }}/bin/windsor; then
