build-event

diff --git a/.github/workflows/cli-pages.yaml b/.github/workflows/cli-pages.yaml
--- a/.github/workflows/cli-pages.yaml
+++ b/.github/workflows/cli-pages.yaml
@@ -19,9 +19,17 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GHTOKEN }}
         run: |
-          curl -X POST \
-            -H "Accept: application/vnd.github.everest-preview+json" \
-            -H "Authorization: token $GH_TOKEN" \
+          curl -L \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GH_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/windsor-hotel/windsorcli/dispatches \
-            -d '{"event_type": "build_event"}'
-            echo "Curl return code: $?"
+            -d '{"event_type":"build_event"}'
+            
+          # curl -X POST \
+          #   -H "Accept: application/vnd.github.everest-preview+json" \
+          #   -H "Authorization: token $GH_TOKEN" \
+          #   https://api.github.com/repos/windsor-hotel/windsorcli/dispatches \
+          #   -d '{"event_type": "build_event"}'
+          #   echo "Curl return code: $?"
